[package]
name = "zkru"
version = "0.1.0"
authors = ["Cam Williams <cam@camwilliams.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
regex = "1"
lazy_static = "1.4.0"